### ISSUE TITLE
Sandbox is enabled for sites with no can't-be-evil header

### ISSUE THREAD

**Issue by njordhov** [newinternetlabs/new-internet-extension#12]
For example, sandbox is enabled on https://apple.com

![image](https://user-images.githubusercontent.com/219448/71950129-09a14300-318b-11ea-9aa4-9ba9d2b84e45.png)

**Comment by larrysalibra** [comment]
@njordhov I'm unable to replicated this on Chrome Version 79.0.3945.117 on macOS. Do you have any other extensions installed. Is apple.com the only site it happens on?

<img width="1017" alt="Screen Shot 2020-01-13 at 9 02 34 PM" src="https://user-images.githubusercontent.com/597182/72258049-0b19b200-3648-11ea-9f3a-6bccf4572ea3.png">

**Comment by njordhov** [comment]
Using Chrome Version 79.0.3945.117 (Official Build) (64-bit) CBE sandbox reports:

    {"https://www.apple.com":{"serverSetsCookie":true,"appSendsCookie":true},"requests":{"https://securemetrics.apple.com":2},"violatedDirectives":{"img-src":2},"version":1}

Google is evil too:

![image](https://user-images.githubusercontent.com/219448/72300152-cc6c0380-3617-11ea-97ab-97f013fba0af.png)

{"https://www.google.com":{"serverSetsCookie":true,"appSendsCookie":true},"requests":{"https://fonts.gstatic.com":28,"https://ssl.gstatic.com":1,"https://www.gstatic.com":2,"https://adservice.google.com":1},"violatedDirectives":{"font-src":28,"img-src":3,"script-src-elem":1},"version":1}

Extensions:
![image](https://user-images.githubusercontent.com/219448/72299401-9037a380-3615-11ea-9335-f5d0488d9c45.png)

CBE is still in effect on Apple.com after disabling the CORS extension, but only on Chrome, not Firefox.

**Comment by larrysalibra** [comment]
I'm still unable to reproduce this. Please re-open if you're still seeing the problem.
