### ISSUE TITLE
Allow blob: URLs as content source

### ISSUE THREAD

**Issue by ViniciusBP** [newinternetlabs/new-internet-extension#15]
The connect-src directive is configured as a wildcard and allow any URLs with a network scheme. 

Why is not allowed to use blob: URIs as content source? I think it should be changed to allow.

**Comment by alansoliditydev** [comment]
I have this problem, too

**Comment by thiagomva** [comment]
I'm having this problem with connect-src and also with object-src directive. I think both should allow blob content.

**Comment by GinaAbrams** [comment]
@larrysalibra would you be able to please comment on this one 🙏

**Comment by larrysalibra** [comment]
@ViniciusBP I'm open to making changes to it. Do you want to send a pull request with the proposed changes?

Alternatively, could you write the CSP expression as you'd like to see it here in the issue? Thanks!

**Comment by thiagomva** [comment]
@larrysalibra just created a pull request changing:
connect-src * to connect-src * data: blob:;
object-src 'self' to object-src 'self' data: blob:;

**Comment by larrysalibra** [comment]
This already was merged and shipped.
