### ISSUE TITLE
Rename can't-be-evil to Cant-Be-Evil

### ISSUE THREAD

**Issue by friedger** [newinternetlabs/new-internet-extension#16]
can't-be-evil does not follow the recommendation of https://tools.ietf.org/html/rfc3864#section-4.1

> Thus, for maximum flexibility, header field names SHOULD further be
   restricted to just letters, digits, hyphen ('-') and underscore ('_')
   characters, with the first character being a letter or underscore.

The header should be `Cant-Be-Evil`.

The capitalization is the same as in #14

**Comment by larrysalibra** [comment]
The next version of the extension will support either `Cant-Be-Evil` or `Can't-Be-Evil` (case insensitive). Thanks for your help on this @friedger !
