### ISSUE TITLE
Apps opting-in to sandbox shouldn't have cookie warning on response

### ISSUE THREAD

**Issue by larrysalibra** [newinternetlabs/new-internet-extension#19]
When apps opt-in to the sandbox, cookies are removed both on request and response. Because apps often don't have control over the responses of servers, there's no need to show a warning that the app used cookies.

We can adjust the behavior of the notification so that when an app opts in to the sandbox, the cookie warning isn't displayed if a server tries to send cookies.

**Comment by njordhov** [comment]
Got cookies?

![image](https://user-images.githubusercontent.com/219448/72400814-37443a00-36ff-11ea-890f-dc516c72b68c.png)

**Comment by larrysalibra** [comment]
@njordhov can you see what the cookie is? I'm not seeing any here

<img width="1207" alt="Screen Shot 2020-01-15 at 2 19 48 PM" src="https://user-images.githubusercontent.com/597182/72409934-18e34a80-37a2-11ea-9c0c-6779fe9f1a94.png">

**Comment by njordhov** [comment]
> @njordhov can you see what the cookie is? I'm not seeing any here

Neither can I, but the Sandbox still reports:

![image](https://user-images.githubusercontent.com/219448/72482668-60be9d80-37b3-11ea-8ae6-113ffbcc1812.png)

PS: I disabled all other browser extensions. No cookies found in the network inspector either.

**Comment by larrysalibra** [comment]
These changes will be in the next release.
