### ISSUE TITLE
Blockstack Connect authentication fails with NIL

### ISSUE THREAD

**Issue by njordhov** [newinternetlabs/new-internet-extension#25]
If NIL is enabled, Blockstack Connect authentication fails:

![image](https://user-images.githubusercontent.com/219448/78648871-794dc980-7871-11ea-97c0-b6036a66a2a0.png)

Disabling NIL allows Connect authentication to complete.

Can be tested at https://dcrypt.app or this specific [dCrypt build](https://5e8c3eb83ccdf6f9daf5f21a--dcrypt.netlify.com)

**Comment by markmhendrickson** [comment]
@larrysalibra we'd love guidance on this as the PBC UX team to improve Connect so it's compatible here, should a change on our end be required

**Comment by larrysalibra** [comment]
Sorry about the slow reply on this. 

Thanks @markmhx and @njordhov for bringing this to my attention. I am able to replicate the issue.

My first thought is that it has something to do with Blockstack Connect accessing an API that's prohibited by the content security policy `sandbox` that the extension enforces.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox

> It applies restrictions to a page's actions including preventing popups, preventing the execution of plugins and scripts, and enforcing a same-origin policy.

I'm going to play around with it to see which settings make the problem go away and what the corresponding "can't be evil" tradeoffs would be. At first glance. I don't see a problem opening a popup that "escapes" the sandbox as long as the browser clearly indicates that it is a different origin. I'll look into it more and report back.

**Comment by larrysalibra** [comment]
These changes have been merged to develop and will be shipped in the next release! Thanks @markmhx and @njordhov for your help!
