### ISSUE TITLE
Land Ho triggers extension alert?  NIL Bug or LH Issue?

### ISSUE THREAD

**Issue by dantrevino** [newinternetlabs/new-internet-extension#4]
We're currently using an iframe to show results.  The extension doesn't show any bad behavior but the icon shows the red alert.  Is this a bug in the extension or an issue that I need to fix in Land Ho? Codebase is here: https://gitlab.com/riot.ai/landho

![Screen Shot 2019-11-12 at 1 26 54 PM](https://user-images.githubusercontent.com/7738/68798179-c7380b80-060a-11ea-8d65-520d7bfe0083.png)

**Comment by larrysalibra** [comment]
Thanks for giving this a try @dantrevino! Where is the iframe showing results from? If it's from the same app origin I don't think it should show up as being evil in the current iteration.

Also, it's cool that this works on Brave! I'd only tested it on Firefox and Chrome!
